### ISSUE TITLE
Use session or not as an option

### ISSUE THREAD

**Issue by ash0080** [fastify/fastify-passport#435]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

1. I am writing a hasura side project, in this application scenario, the auth server only provides the remote schema and the necessary redirect url, the user does not have the opportunity to save or use the session, all the authentication will be done through jwt
2. passport itself supports "disable session"

Based on the above two points, I would like to make it a choice whether to use session or not
but，for now,  If I don't register ‘fastify-secure-session’

```
2022-01-03T06:19:44.289Z *9884 @ElvisMini.local - error: #req-1 Flash plugin requires a valid session.
                         ×Error 500: Flash plugin requires a valid session.
    at Object.<anonymous> (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/fastify-flash@2.0.2/node_modules/fastify-flash/lib/index.js:13:18)
    at hookIterator (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/fastify@3.25.3/node_modules/fastify/lib/hooks.js:237:10)
    at next (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/fastify@3.25.3/node_modules/fastify/lib/hooks.js:164:16)
    at contentSecurityPolicyMiddleware (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/helmet@4.6.0/node_modules/helmet/dist/middlewares/content-security-policy/index.js:124:4)
    at Object.<anonymous> (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/fastify-helmet@5.3.2/node_modules/fastify-helmet/index.js:45:7)
    at hookIterator (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/fastify@3.25.3/node_modules/fastify/lib/hooks.js:237:10)
    at next (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/fastify@3.25.3/node_modules/fastify/lib/hooks.js:164:16)
    at internalNext (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/helmet@4.6.0/node_modules/helmet/dist/index.js:142:6)
    at xXssProtectionMiddleware (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/helmet@4.6.0/node_modules/helmet/dist/middlewares/x-xss-protection/index.js:6:3)
    at internalNext (/Volumes/Root/Users/Elvis/WIP/SeaLight/server/node_modules/.pnpm/helmet@4.6.0/node_modules/helmet/dist/index.js:145:6)
                         & {"req":{"method":"GET","url":"/","hostname":"0.0.0.0:3001","remoteAddress":"127.0.0.1","remotePort":55152},"res":{"statusCode":500}}
2022-01-03T06:19:44.296Z *9884 @ElvisMini.local -  info: #req-1 request completed
                         & {"res":{"statusCode":500},"responseTime":8.393865000456572}
2022-01-03T06:19:45.311Z *9884 @ElvisMini.local - trace: client error
                         ×Error 500: Parse Error: Invalid method encountered
```

Boom ~ 🤷‍♂️

**Comment by climba03003** [comment]
Please provide repro for your issue.

I can see that you are using `flash` which must need `session`. Please try to explicitly disable the `flash` message in option. i.e. `successFlash` and `failureFlash`

**Comment by ash0080** [comment]
> 
 fastify-flash is written in the fastify-passport, not as an additional dependency by me

**Comment by climba03003** [comment]
That's true, Overlooked the dependencies.
Although, most of strategy from passport require session. I think it is a valuable option.

Would you like to send a PR for this issue?

**Comment by airhorns** [comment]
`fastify-passport` has an annoying dependency on a flash system as the original passport did as well. I think we could add an option to mimic the normal passport's disable session functionality though. @ash0080 would you like to send a PR to `fastify-passport` adding support for that option that has the same behaviour as the upstream?

**Comment by ash0080** [comment]
Although I would like to PR, but recently there are too many side projects in writing, I have actually switched to grant after writing this issue this afternoon, and found that grant is much more controllable than passport, although there is no built-in refreshToken method 🤷

**Comment by rluvaton** [comment]
The same issue for me, would love if this could be added :)

BTW, I'm trying to create a new service in our company that uses Fastify (the first one and hopefully can migrate the rest)
