### ISSUE TITLE
@fastify/jwt and @fastify/passport FST_ERR_DEC_ALREADY_PRESENT

### ISSUE THREAD

**Issue by lxhan** [fastify/fastify-passport#880]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

2.3.0

### Node.js version

18.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1

### Description

I installed @fastify/jwt and @fastify/passport plugins but getting an error if I use them both. If I remove one of them everything works good.
My motivation was to use fastify ecosystem as much as possible and I wanted to use passport for oauth2 and jwt to requests.

When running with both plugins getting this error:

```
FastifyError [Error]: The decorator 'user' has already been added!
    at decorateConstructor (/backend/node_modules/fastify/lib/decorate.js:41:11)
    at Object.decorateRequest (/backend/node_modules/fastify/lib/decorate.js:123:3)
    at fastifyJwt (/backend/node_modules/@fastify/jwt/jwt.js:174:13)
    at Plugin.exec (/backend/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/backend/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_DEC_ALREADY_PRESENT',
  statusCode: 500
}
```

I read documentation about plugins and decorators but I don't know if it applies to installed plugins.

### Steps to Reproduce

- Install @fastify/jwt and @fastify/passport
- Register plugins
- Run app

### Expected Behavior

App is not crushing and I can use passport for oauth2 and jwt for signing.

**Comment by climba03003** [comment]
Read the documentation, it already provide a way for customize the `user` field name. So, it won't collide with other plugin.
https://github.com/fastify/fastify-jwt/tree/master#decoratorname
